vpc_cidr           = "10.1.0.0/16"
subnet_cidr        = "10.1.1.0/24"
availability_zone  = "us-east-1b"
vpc_name           = "dev-vpc"
igw_name           = "dev-igw"
route_table_name   = "dev-public-rt"